server:
  port: 8761
spring:
  security:
    user:
      name: dev
      password: dev
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://dev:dev@localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
