server:
  port: 8761
spring:
  security:
    user:
      name: dev
      password: dev
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
  instance:
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: dev
      user.password: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file: ${spring.application.name}.log
